system:
    admin_group:
        field_templates:
            - { template: "@DonfelicePolygonFieldType/ezpolygon.html.twig", priority: 0 }
        fielddefinition_edit_templates:
            - { template: "@DonfelicePolygonFieldType/fieldtypes/edit/ezpolygon.html.twig", priority: 0 }
        fielddefinition_settings_templates:
            - { template: "@DonfelicePolygonFieldType/fieldtypes/view/ezpolygon.html.twig", priority: 0 }
